### ISSUE TITLE
Chrony replacement

### ISSUE THREAD

**Issue by kevinburke** [memorysafety/ntpd-rs#108]
We are currently using chrony to synchronize with AWS clocks. Would this tool be able to replace chrony? If so how would that work, roughly?

**Comment by davidv1992** [comment]
This tool is currently still in active development, and in its current state we would strongly recommend against deploying it anywhere. Once this changes, we will add instructions on how to setup our software as the system ntp daemon.

**Comment by davidv1992** [comment]
We have progressed to the point that it is now possible to use NTPD-rs to synchronize a system. Documentation with respect to how NTPD-rs can be configured can be found in [the documentation](https://github.com/memorysafety/ntpd-rs/blob/main/CONFIGURATION.md). Please let us know if there is anything that is still unclear.

However, do keep in mind that this is still very early release software, and only use it on systems where the risks are acceptable.
