### ISSUE TITLE
Better error handling for well known failure scenarios that require operator intervention

### ISSUE THREAD

**Issue by rnijveld** [memorysafety/ntpd-rs#117]
Some failure modes:
- when the client can't start up because of permissions 
- when the client can't start because of configuration failure
- When a sudden time jump is detected in the middle of normal operation

I think we may want to try and emit specific exit codes for these well known failure modes, so that they can be distinguished from other errors and panics. We also want to specifically make sure that we emit an error level log message before exiting the program to make sure that such a message pops up in a system that monitors the log messages.

**Comment by folkertdev** [comment]
custom exit codes are a bit annoying pre 1.6.1 (see [here](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html#custom-exit-codes-from-main) for a good writeup). I guess what we can do is

```rust
eprintln!("some message");
process::exit(123)
```

wherever we currently `panic!`

should we use/avoid particular exit codes (I know out-of-memory is one to avoid)

**Comment by djc** [comment]
Where you can return through `main()`, I like to have it return `anyhow::Result<()>` which takes care of a bunch of stuff. Might still also want something to replace `panic!()` with more specific handling in cases where returning might not be practical.

**Comment by rnijveld** [comment]
I'm a little bit on the fence about adding anyhow. Outside of main I think it makes more sense to keep using error enums (with thiserror), and in main I feel like we don't have that many error cases to handle, so I would much rather just handle those few cases manually and also set a nice custom exit code with them (which we can't do with anyhow). We could use the termination trait for that, but we could also process::exit if we prefer to keep our MSRV lower.
