### ISSUE TITLE
Client for observing state and dynamically changing configuration

### ISSUE THREAD

**Issue by folkertdev** [memorysafety/ntpd-rs#119]
we have two unix sockets, by default

    /run/ntpd-rs/log-level
    /run/ntpd-rs/config

the log level is unprotected, the config needs additional permissions.

<hr>

we can use https://docs.rs/tokio/latest/tokio/net/struct.UnixStream.html

for sending data over the socket, use https://docs.rs/postcard/latest/postcard/ ? (or send json as bytes?)

<hr>

```
client --set-log-level=debug

client --step-if-bigger=1000 --step-first-updates=10
```

then we also need some observability features, some ideas

```
client peers list # lists all remotes we are connected to
client peers watch # show for each connected peer its `PeerStatus`
```

**Comment by davidv1992** [comment]
I would suggest moving the changing of log-level into config as well, as it can have availability impact depending on what is done with the log output (trace may overwhelm log storage).

Furthermore, I'm missing socket for observing in the list of sockets.

**Comment by folkertdev** [comment]
well we discussed that the configuration that actually changes how the clock behaves (e.g. when to step) should be separate from the logging configuration. These two can then get different permissions (e.g. with user groups). My impression was that you can control the permissions on the socket (it's just a file, after all) and hence there are two sockets: one with minimal permissions that adjusts logs (and perhaps other behavior that does not impact the clock steering), and one with more restrictive permissions that can actually change how clock steering operates (changing peers, when to jump, ect).

**Comment by davidv1992** [comment]
According to my notes and what i remember the discussion was more on splitting the interactive (configuration-changing) part from the non-interactive readout part (e.g. the measurements) so that things like node-exporter don't need excessive permissions to get statistics.
