### ISSUE TITLE
Implement method for exporting metrics to prometheus

### ISSUE THREAD

**Issue by davidv1992** [memorysafety/ntpd-rs#127]
This is hopefully covered well by the socket mechanism needed for #119

**Comment by folkertdev** [comment]
I think this is basically done. You would need a prometheus config that periodically opens the socket to get the current state, and it looks like prometheus has options to do exactly that.

**Comment by davidv1992** [comment]
@folkertdev can you verify with LE that this is indeed sufficient for them?

**Comment by folkertdev** [comment]
response from LE

> In general the main difficulty in writing a Prometheus exporter for a bespoke stats format is not the syntax or the HTTP protocol, but the semantics. In particular, Prometheus has four categories of stat: counters, gauges, histograms, and summaries. Counters never reset for the lifetime of the process; it's useful if bespoke stats follow that same semantic. Histogram buckets are annotated with labels that indicate the upper end of the bucket, and count all events in that bucket _and all buckets below_. Histograms also include sum and count counters, naturally. The advantage of providing histograms over summaries (e.g. 99th percentile, etc) is that histograms can be accurately aggregated across multiple instances, while per-instance summaries cannot.
> 
> I would encourage you to at least adopt the Prometheus semantics, and ideally also the export format, which is quite simple, for instance:
> 
>   ```
>   # HELP grpc_server_handled_total Total number of RPCs completed on the server, regardless of success or failure.
>   # TYPE grpc_server_handled_total counter
>   grpc_server_handled_total{grpc_code="OK",grpc_method="Check",grpc_service="grpc.health.v1.Health",grpc_type="unary"} 1
>   ```
> 
> As for the distinction between Unix sockets and HTTP, it is not particularly important; though I would note that it's possible to write an HTTP/1.0 "server" that does not bother parsing client requests at all, and simply splats out "HTTP/1.0 OK\r\n\r\n<body>" to any connection request.

**Comment by folkertdev** [comment]
Currently, we can use the client like this 

    folkertdev@folkertdev ~/t/n/ntpd-rs (main)> cargo build && sudo target/debug/ntp-client peers
    [
      {
        "Observable": {
          "statistics": {
            "offset": 0.00024183699866799568,
            "delay": 0.008722740460355472,
            "dispersion": 7.9375019911531135,
            "jitter": 3.814697266513178e-6
          },
          "reachability": 1,
          "uptime": {
            "secs": 11,
            "nanos": 139363161
          },
          "poll_interval": {
            "secs": 16,
            "nanos": 0
          },
          "peer_id": 3589249548
        }
      },
      {
        "Observable": {
          "statistics": {
            "offset": 0.0019689977639282584,
            "delay": 0.014038344615613657,
            "dispersion": 7.937502046101145,
            "jitter": 3.814697266513178e-6
          },
          "reachability": 1,
          "uptime": {
            "secs": 11,
            "nanos": 127481359
          },
          "poll_interval": {
            "secs": 16,
            "nanos": 0
          },
          "peer_id": 2928306951
        }
      }
    ]

Prometheus can poll the socket (that is what the client does, it just connects to the socket, gets this message, and the socket is closed again). Is there other formatting we need besides this json then?

**Comment by jsha** [comment]
Here's how that would look in the Prometheus export format, with JSON keys flattened into labels and durations expressed in float64 seconds:

```
# TYPE ntp_peer_offset gauge
ntp_peer_offset{peer_id="3589249548"} 0.00024183699866799568
# TYPE ntp_peer_delay gauge
ntp_peer_delay{peer_id="3589249548"} 0.008722740460355472
# TYPE ntp_peer_dispersion gauge
ntp_peer_dispersion{peer_id="3589249548"} 7.937502046101145
# TYPE ntp_peer_jitter gauge
ntp_peer_jitter{peer_id="3589249548"} 3.814697266513178e-6
# TYPE ntp_peer_reachability  gauge
ntp_peer_reachability{peer_id="3589249548"} 1
# TYPE ntp_peer_uptime gauge
ntp_peer_uptime{peer_id="3589249548"} 11.139363161
# TYPE ntp_peer_poll_interval gauge
ntp_peer_poll_interval{peer_id="3589249548"} 16

ntp_peer_offset{peer_id="2928306951"} 0.0019689977639282584
ntp_peer_delay{peer_id="2928306951"} 0.014038344615613657
ntp_peer_dispersion{peer_id="2928306951"} 7.937502046101145
ntp_peer_jitter{peer_id="2928306951"} 3.814697266513178e-6
ntp_peer_reachability{peer_id="2928306951"} 1
ntp_peer_uptime{peer_id="2928306951"} 11.127481359
ntp_peer_poll_interval{peer_id="2928306951"} 16
```

I'd also include the "system" metrics:

```
# TYPE ntp_system_poll_interval gauge
ntp_system_poll_interval 4
# TYPE ntp_system_precision gauge
ntp_system_precision 3.814697266513178e-06
# TYPE ntp_system_leap_indicator gauge
ntp_system_leap_indicator{type="NoWarning"} 1
```

Looking at the current stats, I see my comment about semantics is less relevant than I thought it would be, since all the metrics here are gauges, not counters. But using seconds consistently is helpful.

Rather than the numeric peer_id, it would be most useful to export the formatted IP address.

The `reachability` metric is a little strange to express as a numeric gauge, since it's actually a bitfield. The way I would express this in Prometheus would be a simple 1/0 gauge to indicate whether ntpd considers a peer reachable, and a counter of poll attempts for that peer with labels `{result="success"}` or `{result="timeout"}` depending on the result of that poll. That makes it easy to graph the success percentage over a period of time. But this part is fairly low priority.

**Comment by folkertdev** [comment]
Thanks for that detailed description. Two followup questions

- could we put all those `TYPE` definitions at the top, or do they have to be interspersed with the (first?) actual use?
- could prometheus poll the client instead, running e.g. `ntp-client prometheus` at a set interval to get the prometheus output. That would mean the prometheus formatting logic can all live in the client and we can continue to use serde/json for communication on the socket.
