### ISSUE TITLE
Discussion: Failure mode upon detecting programming errors

### ISSUE THREAD

**Issue by davidv1992** [memorysafety/ntpd-rs#24]
There are currently a few, and probably in the future will be a few more, places where we can and do do checks that essentially represent invariants that should always hold, regardless of any input provided from external sources. As such, failure of these checks directly indicate bugs in our code, and the question then becomes what should the behaviour of these checks be in release builds.

Given the specific nature of NTP, especially for an NTP client, I personally am of the opinion that the safer option is to actively blow up upon detection of such errors. This is because, assuming we detected it early enough, the system time now is hopefully reasonably correct, and in that case without corrections shouldn't drift to the point in the short term, and at the same time blowing up makes the issue very visible to whomever is managing the server running the client. However, silently ignoring the error or trying to work around it could result in incorrect steering of the clock (since the software is now in a state that was never anticipated), and incorrect steering could potentially result in significant clock deviation from UTC fairly quickly, and furthermore is far less visible to whomever is managing the server running the client, increasing the potential for a faulty situation to last for a significant time interval.

Is this the view we want to take as project, or are there arguments to the contrary that I am forgetting about here.

**Comment by djc** [comment]
My question is what you mean by blowing up exactly. IMO we should try pretty hard to avoid killing a long-running process (daemon), though killing a short-running CLI should definitely be fine. Of course we should never fail silently; I'd recommend adopting the tracing crate early and making sure we emit error logs in these kinds of circumstances.

**Comment by davidv1992** [comment]
By blowing up I do mean killing the daemon itself. Active steering in the wrong direction can be so harmful that I think it is something to be avoided, and if we detect a programming error, at least in my view, we can't reasonably argue that that won't happen.

**Comment by djc** [comment]
Okay, I guess that's fair.
