### ISSUE TITLE
how to disable backward jump ?

### ISSUE THREAD

**Issue by usrtax** [memorysafety/ntpd-rs#353]
if ntpd can `tinker stepback 0`

https://stackoverflow.com/questions/35068445/is-there-a-way-to-ensure-ntp-synced-clock-never-moves-backwards

> Let say I have code that uses the clock to generate ids. Or I have code that calculates time elapsed since an event happened. Or any other logic that expects system time to only move forwards, never backwards. If time does move backwards, and the program notices it, lets say it crashes or hangs.
>
> I'd like to use an NTP service with such programs. Is there a way that NTP can be configured so that it is guaranteed never to adjusts time backwards? Slowing down the system clock would be fine.

**Comment by davidv1992** [comment]
There is no good way to do this currently, I have reworked our configuration mechanism a bit in the above PR to start allowing this. Once this lands in master, this issue should automatically be closed, and this will be possible on master by simply setting a 0 backwards panic threshold.
