### ISSUE TITLE
Kernel-level send timestamping

### ISSUE THREAD

**Issue by davidv1992** [memorysafety/ntpd-rs#61]
Figure out a good api and implement kernel-level send timestamping (stretch goal)

**Comment by folkertdev** [comment]
The docs note 

https://docs.kernel.org/networking/timestamping.html

> SOF_TIMESTAMPING_TX_SOFTWARE:
> Request tx timestamps when data leaves the kernel. These timestamps are generated in the device driver as close as possible, but always prior to, passing the packet to the network interface. Hence, they require driver support and may not be available for all devices. This flag can be enabled via both socket options and control messages.
> 
> SOF_TIMESTAMPING_TX_SCHED:
> Request tx timestamps prior to entering the packet scheduler. Kernel transmit latency is, if long, often dominated by queuing delay. The difference between this timestamp and one taken at SOF_TIMESTAMPING_TX_SOFTWARE will expose this latency independent of protocol processing. The latency incurred in protocol processing, if any, can be computed by subtracting a userspace timestamp taken immediately before send() from this timestamp. On machines with virtual devices where a transmitted packet travels through multiple devices and, hence, multiple packet schedulers, a timestamp is generated at each layer. This allows for fine grained measurement of queuing delay. This flag can be enabled via both socket options and control messages.
> 
> SOF_TIMESTAMPING_TX_ACK:
> Request tx timestamps when all data in the send buffer has been acknowledged. This only makes sense for reliable protocols. It is currently only implemented for TCP. For that protocol, it may over-report measurement, because the timestamp is generated when all data up to and including the buffer at send() was acknowledged: the cumulative acknowledgment. The mechanism ignores SACK and FACK. This flag can be enabled via both socket options and control messages.

this is part of `SO_TIMESTAMPING`. We currently use `SO_TIMESTAMPNS`, I'm not sure what the tradeoffs are there. is `SO_TIMESTAMPING` less accurate somehow?
